version: '3'

services:
  intervention-service:
    environment:
      BANK_CLIENT_ID: ${BANK_CLIENT_ID}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      KAFKA_SERVER: ${KAFKA_SERVER}
    build: .
    ports:
      - "9001-9050:8080"
    deploy:
      replicas: 2
    networks:
      - onboardingbank
networks:
  onboardingbank:
    external: true